### ISSUE TITLE
Broken link to documentation

### ISSUE THREAD

**Issue by aranguiz82** [RedHatInsights/rhproxy-engine#56]
The link to Insight Proxy Notes in README is broken. 
I think the correct link is [...doc/NOTES.md](https://github.com/RedHatInsights/rhproxy-engine/blob/main/doc/NOTES.md)

<img width="538" alt="Captura de pantalla 2024-11-13 a la(s) 5 07 13 p m" src="https://github.com/user-attachments/assets/b11de6cc-601d-4de9-a3e6-4832161130a3">

**Comment by jeromemarc** [comment]
Fix in https://github.com/RedHatInsights/rhproxy-engine/pull/65
